# Generated by Django 5.0 on 2024-02-11 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_company_slug_complaint_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='slug',
            field=models.SlugField(default='fef', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='complaint',
            name='slug',
            field=models.SlugField(default='ded', unique=True),
            preserve_default=False,
        ),
    ]
