# Generated by Django 5.0.6 on 2024-06-03 23:57

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to=api.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to=api.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='user',
            name='userpic',
            field=models.ImageField(default='default/userpic.jpg', upload_to=api.models.userpic_path),
        ),
    ]
